openapi: 3.0.0
info:
  title: Evidos â€“ Signhost REST API - OpenAPI v3
  description: 'Signing online documents - Easy and legally valid'
  contact: {}
  version: '1.0'
servers:
  - url: 'https://api.signhost.com/api'
paths:
  '/transaction/{transactionId}':
      get:
        description: Get the transacton
        responses:
          '401':
            description: 	Not authorized to access the specified transaction
          '410':
            description: The transaction details are no longer available and as a result the returned JSON only contains partial historical data. This happens when we cleaned the transaction for example due to reaching an end status (any status above 30), or the expiration dates have expired.
          '200':
            description: 200 OK!
            content:
              application/json:
                example:
                  Id: 67b9e140-b0f6-4c36-9b35-977041968185
                  Status: 20
                  Files:
                    Contract.pdf:
                      Links:
                        - Rel: file
                          Type: application/pdf
                          Link: 'https://api.signhost.com/api/transaction/67b9e140-b0f6-4c36-9b35-977041968185/file/Contract.pdf'
                      DisplayName: ArbeidsContract 2016
                    Algemenevoorwaarden:
                      Links:
                        - Rel: file
                          Type: application/pdf
                          Link: 'https://api.signhost.com/api/transaction/67b9e140-b0f6-4c36-9b35-977041968185/file/Algemenevoorwaarden'
                      DisplayName: Algemene voorwaarden
                  Seal: true
                  Signers:
                    - Id: e0b39ec0-e0c6-45d9-bf0d-ae8cafbe2f48
                      Expires: null
                      Email: user@example.com
                      Mobile: '+31612345678'
                      Iban: null
                      BSN: null
                      RequireScribbleName: false
                      RequireScribble: true
                      RequireEmailVerification: true
                      RequireSmsVerification: true
                      RequireDigidVerification: false
                      RequireSurfnetVerification: false
                      SendSignRequest: true
                      SendSignConfirmation: null
                      SignRequestMessage: 'Hello, could you please sign this document? Best regards, Jay Doe'
                      DaysToRemind: 15
                      Language: en-US
                      ScribbleName: Jay Doe
                      ScribbleNameFixed: false
                      Reference: 'Client #123'
                      ReturnUrl: 'http://signhost.com'
                      Activities:
                        - Id: 91709d15-df2e-48a1-ac90-276f0360ce08
                          Code: 103
                          Activity: Opened
                          CreatedDateTime: '2016-06-15T23:33:04.1965465+02:00'
                        - Id: 04adfda3-dd35-4f4d-af34-d2a08a4434f6
                          Code: 203
                          Activity: Signed
                          CreatedDateTime: '2016-06-15T23:38:04.1965465+02:00'
                      RejectReason: null
                      SignUrl: 'http://ui.signhost.com/sign/d959e67b-acf8-4a49-8811-9b62f0b450af'
                      SignedDateTime: null
                      RejectDateTime: null
                      CreatedDateTime: '2016-06-15T23:33:04.1965465+02:00'
                      ModifiedDateTime: '2016-06-15T23:33:04.1965465+02:00'
                      Context: null
                  Receivers:
                    - Id: df52316c-6671-4f39-9b9e-b524cc36ef93
                      Name: John Doe
                      Email: user@example.com
                      Language: en-US
                      Message: 'Hello, please find enclosed the digital signed document. Best regards, John Doe'
                      Reference: null
                      Activities: null
                      CreatedDateTime: '2016-06-15T23:33:04.1965465+02:00'
                      ModifiedDateTime: '2016-06-15T23:33:04.1965465+02:00'
                      Context: null
                  Reference: 'Contract #123'
                  PostbackUrl: 'http://example.com/postback.php'
                  SignRequestMode: 2
                  DaysToExpire: 30
                  SendEmailNotifications: true
                  CreatedDateTime: '2016-06-15T23:33:04.1965465+02:00'
                  ModifiedDateTime: '2016-06-15T23:33:04.1965465+02:00'
                  CanceledDateTime: null
                  Context: null

      parameters:
      - name: transactionId
        in: path
        description: 'The ID the transaction to GET'
        required: true
        schema:
          type: string
          example: '67b9e140-b0f6-4c36-9b35-977041968185'
      delete:
        description: Deletes the transaction
        responses:
          '200':
            description: 'The transaction is succesfully deleted'
          '400':
            description: 'The transaction could not be deleted'
  '/transaction':
    post:
      summary: Create Transaction - Example
      description: ''
      operationId: CreateTransaction-Example
      parameters:
        - name: Application
          in: header
          description: ''
          required: true
          style: simple
          schema:
            type: string
            example: APPKey NAME Your_App_Key
        - name: Authorization
          in: header
          description: ''
          required: true
          style: simple
          schema:
            type: string
            example: APIKey Your_API_Key
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTransaction-ExampleRequest'
            example:
              Signers:
                - Email: EnterAValidEMailAddressHere
                  ScribbleName: Example
                  SendSignRequest: false
                  SignRequestMessage: 'Hello, this is an example! Please sign this!'
                  Verifications:
                    - Type: PhoneNumber
                      Number: '+31123456789'
                    - Type: Scribble
                      RequireHandsignature: true
        required: true
      responses:
        '200':
          description: ''
          headers: {}
          content:
            text/plain:
              schema:
                type: object
      deprecated: false
      servers:
        - url: 'https://api.signhost.com/api'
          variables: {}
  '/transaction/{transactionId}/file/{fileId}/':
    put:
      summary: Add File - Example
      description: ''
      operationId: AddFile-Example
      parameters:
        - name: transactionId
          in: path
          description: 'The ID the transaction add the file'
          required: true
          schema:
            type: string
            example: '67b9e140-b0f6-4c36-9b35-977041968185'
        - name: fileId
          in: path
          description: 'Id of the file'
          required: true
          schema:
            type: string
            example: 'Contract.pdf'
        - name: Content-Type
          in: header
          description: ''
          required: true
          style: simple
          schema:
            type: string
            example: application/pdf
        - name: Application
          in: header
          description: ''
          required: true
          style: simple
          schema:
            type: string
            example: APPKey NAME Your_App_Key
        - name: Authorization
          in: header
          description: ''
          required: true
          style: simple
          schema:
            type: string
            example: APIKey Your_API_Key
      responses:
        '200':
          description: 'The contents of the file is returned in the body.'
          headers: {}
          content:
            application/pdf:
              schema:
                type: object
      deprecated: false
      servers:
        - url: 'https://api.signhost.com/api'
          variables: {}
  '/transaction/':
    put:
      summary: Start Transaction - Example
      description: ''
      operationId: StartTransaction-Example
      parameters:
        - name: Application
          in: header
          description: ''
          required: true
          style: simple
          schema:
            type: string
            example: APPKey NAME Your_App_Key
        - name: Authorization
          in: header
          description: ''
          required: true
          style: simple
          schema:
            type: string
            example: APIKey Your_API_Key
      responses:
        '200':
          description: ''
          headers: {}
          content:
            text/plain:
              schema:
                type: object
      deprecated: false
      servers:
        - url: 'https://api.signhost.com/api'
          variables: {}
components:
  schemas:
    CreateTransaction-ExampleRequest:
      title: CreateTransaction-ExampleRequest
      required:
        - Signers
      type: object
      properties:
        Signers:
          type: array
          items:
            type: object
          description: ''
      example:
        Signers:
          - Email: valid@example.org
            ScribbleName: ExampleMan
            SendSignRequest: false
            SignRequestMessage: 'Hello, this is an example! Please sign this!'
            Verifications:
              - Type: PhoneNumber
                Number: '+31123456789'
              - Type: Scribble
                RequireHandsignature: true
tags: []

